#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = TestDocument
APP_NAME = TestDocument
TestDocument_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DOMAIN = USER


#
# Resource files
#
TestDocument_RESOURCE_FILES = \
Resources/TestDocument.gorm \
Resources/Doctype1Document.gorm \
Resources/Doctype2Document.gorm 


#
# Header files
#
TestDocument_HEADER_FILES = \
AppController.h \
AppDelegate.h \
Doctype1Document.h \
TestDocumentController.h \
TestWindowController.h \
Doctype2Document.h \
TestWindow2Controller.h \
Doctype1.h \
Doctype2.h \
CustomInitializer.h

#
# Objective-C Class files
#
TestDocument_OBJC_FILES = \
AppController.m \
AppDelegate.m \
Doctype1Document.m \
TestDocumentController.m \
TestWindowController.m \
Doctype2Document.m \
TestWindow2Controller.m \
Doctype1.m \
Doctype2.m \
CustomInitializer.m

#
# Other sources
#
TestDocument_OBJC_FILES += \
TestDocument_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
